plugins {
    id 'java'
}

group = 'com.arkflame'
version = '1.0.0'

repositories {
    mavenCentral()
    flatDir {
        dirs 'libraries'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

dependencies {
    // Libraries
    compileOnly files("${rootDir}/libraries/HytaleServer.jar")
    
    // Tests
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}